### ISSUE TITLE
Please help...

### ISSUE THREAD

**Issue by michelinok** [gaionim/rpitx#3]
Hi, how can i use setTime.py ?
I'm using rpitx, and found this fork utility...can you explain how to set time (for example) one year in the future?
Many thanks

Michele

PS: If you want, you can write in italian... :P

**Comment by gaionim** [comment]
Per ora era solo un test e non funziona, vedi https://github.com/F5OEO/rpitx/issues/3
Siccome l'orologio non si accorge nemmeno della trasmissione, non sono andato più avanti....

L'idea era preparare i dati, scriverli su un file e darli in pasto a rpitx.
Ho chiesto di espandere ( in basso ) la frequenza, ma sembra ci siano problemi per la frequenza troppo bassa.

Se vuoi provare basta usare una data/ora arbitraria
start = datetime.datetime(.......) 
o scrivere direttamente il file "a mano" .

**Comment by michelinok** [comment]
Nei commenti vedo che è scesa a 4khz…

Sono ignorante in materia..potresti spiegarmi?

Grazie infinite per la pazienza!

Michele

Da: Mauro [mailto:notifications@github.com] 
Inviato: lunedì 29 agosto 2016 18:21
A: gaionim/rpitx
Cc: michelinok; Author
Oggetto: Re: [gaionim/rpitx] Please help... (#3)

Per ora era solo un test e non funziona, vedi F5OEO#3 https://github.com/F5OEO/rpitx/issues/3 
Siccome l'orologio non si accorge nemmeno della trasmissione, non sono andato più avanti....

L'idea era preparare i dati, scriverli su un file e darli in pasto a rpitx.
Ho chiesto di espandere ( in basso ) la frequenza, ma sembra ci siano problemi per la frequenza troppo bassa.

Se vuoi provare basta usare una data/ora arbitraria
start = datetime.datetime(.......) 
o scrivere direttamente il file "a mano" .

**Comment by F5OEO** [comment]
@gaionim , your script is working and set my clock ! You should make a pull request on your python script.

**Comment by gaionim** [comment]
glad to see it works,  can I ask how ?
How long the wire ?   Some LC to filter ?

Next days I'll look for my pi and retry,    daylight savings time is coming......

**Comment by gaionim** [comment]
@michelinok 
quando avevo provato non aveva funzionato, ma F5OEO dice che funziona, quindi tocca credergli
e riprovare.
Nei prossmi giorni cercherò il mio raspy e riproverò, magari col programma aggiornato.
Se funziona vedrò di mettere un parametro da riga di comando per impostare la data/ora
oppure un offset.
A memoria se lanci il comando dovrebbe fare tutto da solo, con l'ora attuale.
Mi sembrava di aver verificato che sul pin ci fosse il segnale, anche se l'onda non era proprio sinusoidale e la mia strumentazione non proprio ottimale per verificare la frequenza.

**Comment by michelinok** [comment]
Sarebbe grandioso!

Il 30 ago 2016 22:47, "Mauro" notifications@github.com ha scritto:

**Comment by gaionim** [comment]
Per me funziona ed è stato importato in upstream da F5OEO,
in caso di problemi specifici, apri altro caso con i dettagli. 
NB
a me funziona con circa 6m di filo telefonico ( avevo quello e non ho ritenuto di tagliarlo)
arrotolato e posto vicino all'orologio.
Sia su gpio18 ( senza fare niente) sia su gpio4 ( con apposito parametro )
vedi
./setTime.py -h    per help 

NB
il mio orologio sembra non sia sempre in ascolto, quindi se non vedi segnale, prova
- spegnere e riaccendere radio ( nella mia freccia in basso per 3 sec, sparisce l'antenna, frecci ain alto per 3 sec, ricompare antenna lampeggiante ed inizia la ricezione )
  - se non funziona, reset e parte "in ascolto", 

in entrambi i casi ci vogliono  circa 3 minuti per la sincronizzazione,
credo che il primo si perda, il secondo si allinei ed il terzo venga letto correttamente.
